name: "My workflow"

on:
  
  workflow_dispatch:
  
  push:
  
jobs:
 
   build:
     
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     
     - uses: actions/hello-world@v1
